name: Add Test Text to README

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to push changes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add test text to README
        run: |
          # Get current timestamp
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          
          # Add test text with timestamp to README.md
          echo "" >> README.md
          echo "Test text added at: $TIMESTAMP" >> README.md
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Add test text to README [automated]"
      
      - name: Push changes
        run: |
          git push origin main

